---
- hosts: websever
  become: yes
  tasks:
      
    - name: login to jfrog
      shell: docker login -u ssuresh@agile1.com -p Hiqode@272311 jfrog2026.jfrog.io 
    
    - name: pull an image
      shell: docker pull jfrog2026.jfrog.io/imagedeploy/dockeransi:latest

    - name: remove container
      shell: docker rm -f devopsAppDeploy
        
    - name: create a application container
      shell: docker run -id --name devopsAppDeploy -p 8111:8080 jfrog2026.jfrog.io/imagedeploy/dockeransi:latest
 
   
